{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  labels:
    {{- include "distributed-workload-platform.labels" . | nindent 4 }}
data:
  init.sql: |
    {{- range .Values.postgres.initDatabases }}
    CREATE DATABASE {{ . }};
    {{- end }}
{{- end }}