{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-server
  labels:
    {{- include "prefect.labels" . | nindent 4 }}
    app: prefect-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-server
  template:
    metadata:
      labels:
        app: prefect-server
        {{- include "prefect.labels" . | nindent 8 }}
    spec:
      containers:
        - name: prefect-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["prefect", "server", "start"]
          args:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - {{ .Values.port | quote }}
          env:
            - name: RAY_ADDRESS
              value: {{ .Values.rayAddress | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
